apiVersion: v1
kind: Service
metadata:
  name: svc-demo-golang
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: demo-golang