name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Welcome developer
      run: echo welcome developer!

    - name: Login to Azure ACR
      uses: docker/login-action@v1 
      with:
        registry: acrvinvli01.azurecr.io
        username: ${{ secrets.ACRUSERNAME }}
        password: ${{ secrets.ACRTOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        # file: ./Dockerfile
        push: true
        tags: demo-golang:v0.0.1
