name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: check out source code
      uses: actions/checkout@v2
      
    - name: Login to Azure ACR
      uses: docker/login-action@v1 
      with:
        registry: acrvinvli01.azurecr.io
        username: ${{ secrets.ACRUSERNAME }}
        password: ${{ secrets.ACRTOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./demo-golang
        # push: true
        tags: acrvinvli01.azurecr.io/demo-golang:v0.0.1,acrvinvli01.azurecr.io/demo-golang:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}